# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee36d09d91bccb9467ef2fd1d40cd0b1cf3b4bb90efd8dfcae693311dcd0ae8188fc35500b78342ad76c0114b3bdfe664164bbd98781b46a709c8fffb7a3ad5

test:
  secret_key_base: 335e729a3c1eb7ef2fd4e1a38a9fdda1e5e8bf44399d1e8a0f91404fe9a73c73a36f68ac3555805a616bc49f04b6c46ed770cd7e6dab11567afc40f47caca896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
